version: '3'
services:
  node1:
    image: hbbft-node:latest
    command: peer_node -b node1:8001 -r node2:8002 -r node3:8003
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    container_name: hbb-node1
  node2:
    image: hbbft-node:latest
    command: peer_node -b node2:8002 -r node1:8001 -r node3:8003
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    container_name: hbb-node2
    depends_on:
      - node1
  node3:
    image: hbbft-node:latest
    command: peer_node -b node3:8003 -r node1:8001 -r node2:8002
    ports:
      - "8003:8003"
    networks:
      - mynetwork
    container_name: hbb-node3
    depends_on:
      - node1
      - node2
networks:
  mynetwork:
