version: '3'
services:
  node1:
    image: hbbft-node:latest
    command: bash -c "tc qdisc add dev eth0 root netem rate 1mbit && peer_node -b node1:8001 -r node2:8002 -r node3:8003"
    # command: peer_node -b node1:8001 -r node2:8002 -r node3:8003
    ports:
      - "8001:8001"
    networks:
      - mynetwork
    container_name: hbb-node1
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
  node2:
    image: hbbft-node:latest
    command: bash -c "tc qdisc add dev eth0 root netem rate 1mbit && peer_node -b node2:8002 -r node1:8001 -r node3:8003"
    # command: peer_node -b node2:8002 -r node1:8001 -r node3:8003
    ports:
      - "8002:8002"
    networks:
      - mynetwork
    container_name: hbb-node2
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
    depends_on:
      - node1
  node3:
    image: hbbft-node:latest
    # set bandwidth 1Mbps and delay 100ms
    command: bash -c "tc qdisc add dev eth0 root netem rate 1mbit && peer_node -b node3:8003 -r node2:8002 -r node4:8001"
    # command: bash -c "tc qdisc add dev eth0 root netem rate 1mbit delay 50ms && peer_node -b node3:8003 -r node2:8002 -r node1:8001"
    # command: peer_node -b node3:8003 -r node1:8001 -r node1:8001
    ports:
      - "8003:8003"
    networks:
      - mynetwork
    container_name: hbb-node3
    privileged: true
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
    depends_on:
      - node2
networks:
  mynetwork:
